Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = 'web01'
    web.vm.network :private_network, ip: "172.20.10.15"
    web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    web.vm.synced_folder "./html", "/var/www/html"

    web.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end

    db.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = 'db01'
    db.vm.network :private_network, ip: "172.20.10.16"

    db.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end

    db.vm.provision "shell", path: "db.sh"
  end

end
